name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: nikeee/docfx-action@v1.0.0
      name: init docs
      with:
        args: init
        
    - uses: nikeee/docfx-action@v1.0.0
      name: build docs
      with:
        args: /github/workspace/docfx_project/docfx.json --serve

    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: docfx_project/_site 
        GH_PAT: ${{ secrets.GH_PAT }}
