name: Build github pages documentation

on:
  push:
    branches: [ master ]

jobs:
  build_docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: nikeee/docfx-action@v1.0.0
      name: build docs
      with:
        args: ./docfx.json --serve

    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: _site 
        GH_PAT: ${{ secrets.GH_PAT }}
