name: .NET Core Build

on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest, ubuntu-16.04]
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{matrix.os}}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.7.2
        with:
         dotnet-version: 5.0.100
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Run unit tests
        run: dotnet test --no-build --configuration Release

      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: docs/docfx.json

      # Publish generated site using GitHub Pages
      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        env:
          BUILD_DIR: _site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
